### ISSUE TITLE
[Solved] Crashes the Brave Browser

### ISSUE THREAD

**Issue by mcnaveen** [wong2/bing-sidebar-for-chrome#4]
I tried this extension and when I try to click on the icon, it instantly crashes the browser.

1.52.122 Chromium: 114.0.5735.110 (Official Build) (arm64)

**Comment by wong2** [comment]
Does your Brave have this icon?
<img width="338" alt="image" src="https://github.com/wong2/bing-chat-sidebar-for-chrome/assets/321947/82394384-3961-4603-93b2-c14a4e13ef66">

**Comment by mcnaveen** [comment]
Here is a quick recording
https://github.com/wong2/bing-chat-sidebar-for-chrome/assets/8493007/8c6346ac-905a-435c-b98f-7f576fd2fcf1

**Comment by wong2** [comment]
Can you try upgrade brave to latest version? I've tested it on 
[Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (arm64)]

**Comment by adarakchian** [comment]
I confirm the issue with the latest Brave
[Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (64-bit)]

EDIT: installed from source, everything works fine. Perhaps the version in the Chrome store has not been updated yet

**EDIT2: make sure that in the Brave settings, you have the "Show Sidebar" setting on "Always" (it is "Never" by default). Otherwise, it will crash.**

**Comment by wong2** [comment]
Got it!

**Comment by mcnaveen** [comment]
Will check and update asap
